// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.Skyboxes
{
    public static partial class SkyboxShaderTextureHorizonKeys
    {
        public static readonly ObjectParameterKey<Texture> Texture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Color4> AlphaColor = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> ZeroColor = ParameterKeys.NewValue<Color4>();
    }
}
