// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    internal static partial class VRFOVEffectKeys
    {
        public static readonly ValueParameterKey<Color3> Color = ParameterKeys.NewValue<Color3>(new Color3(0f,0f,0f));
        public static readonly ValueParameterKey<float> Radius = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> Intensity = ParameterKeys.NewValue<float>(1f);
        public static readonly ValueParameterKey<float> VerticalScale = ParameterKeys.NewValue<float>(1f);
    }
}
